[CoreRedirects]
; OLD
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_RotateTo",NewName="/Script/UnrealHelperLibrary.BTT_TurnTo")
+FunctionRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_TurnTo.SetupPreset_90_180",NewName="/Script/UnrealHelperLibrary.BTT_TurnTo.SetupPreset_Recommended_90_180")
+FunctionRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_TurnTo.SetupPreset_Recommended_90_180",NewName="/Script/UnrealHelperLibrary.BTT_TurnTo.SetupPreset_Default_90_180")

+ClassRedirects=(OldName="BTComposite_RandomSelector",NewName="BTC_RandomSelector")

; migration to module UHLAI
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_Base",NewName="/Script/UHLBehaviorTree.BTD_Base")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_CheckGASGameplayTagsOnActor",NewName="/Script/UHLBehaviorTree.BTD_CheckGASGameplayTagsOnActor")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_InAngle",NewName="/Script/UHLBehaviorTree.BTD_InAngle")
+StructRedirects=(OldName="/Script/UnrealHelperLibrary.AngleRange",NewName="/Script/UHLBehaviorTree.AngleRange")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_InRange",NewName="/Script/UHLBehaviorTree.BTD_InRange")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_LoopRandomCount",NewName="/Script/UHLBehaviorTree.BTD_LoopRandomCount")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_RandomChance",NewName="/Script/UHLBehaviorTree.BTD_RandomChance")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_TimeLimitRandom",NewName="/Script/UHLBehaviorTree.BTD_TimeLimitRandom")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTS_GameplayFocus",NewName="/Script/UHLBehaviorTree.BTS_GameplayFocus")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_ClearFocus",NewName="/Script/UHLBehaviorTree.BTT_ClearFocus")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_DebugPrintBBValue",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintBBValue")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_DebugPrintString",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintString")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_FireGameplayEvent",NewName="/Script/UHLBehaviorTree.BTT_FireGameplayEvent")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_InvokeGameplayAbility",NewName="/Script/UHLBehaviorTree.BTT_InvokeGameplayAbility")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_PlayAnimMontage",NewName="/Script/UHLBehaviorTree.BTT_PlayAnimMontage")
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.ETaskNodeEndPolicy",NewName="/Script/UHLBehaviorTree.ETaskNodeEndPolicy")

+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_SetBBValue",NewName="/Script/UHLBehaviorTree.BTT_SetBBValue")
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.ESetBBValue_MathOperations",NewName="/Script/UHLBehaviorTree.EUHL_MathOperations")


+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_TurnTo",NewName="/Script/UHLBehaviorTree.BTT_TurnTo")
; ~migration to module UHLAI

+ClassRedirects=(OldName="/Script/UHLBehaviorTree.UHLAIBlueprintLibrary",NewName="/Script/UHLBehaviorTree.UHLBTBlueprintLibrary")
+StructRedirects=(OldName="/Script/UHLBehaviorTree.OperationOnBBValue",NewName="/Script/UHLBehaviorTree.UHLBTOperationOnBBValue")

; Redirect classes moved from UHLAI -> UHLBehaviorTree
; BT Tasks
+ClassRedirects=(OldName="/Script/UHLAI.BTT_TurnTo",NewName="/Script/UHLBehaviorTree.BTT_TurnTo")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_FireGameplayEvent",NewName="/Script/UHLBehaviorTree.BTT_FireGameplayEvent")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_SetBBValue",NewName="/Script/UHLBehaviorTree.BTT_SetBBValue")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_InvokeGameplayAbility",NewName="/Script/UHLBehaviorTree.BTT_InvokeGameplayAbility")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_PlayAnimMontage",NewName="/Script/UHLBehaviorTree.BTT_PlayAnimMontage")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_DebugPrintBBValue",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintBBValue")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_ClearFocus",NewName="/Script/UHLBehaviorTree.BTT_ClearFocus")
+ClassRedirects=(OldName="/Script/UHLAI.BTT_DebugPrintString",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintString")

; BT Services
+ClassRedirects=(OldName="/Script/UHLAI.BTS_GameplayFocus",NewName="/Script/UHLBehaviorTree.BTS_GameplayFocus")

; BT Decorators
+ClassRedirects=(OldName="/Script/UHLAI.BTD_Base",NewName="/Script/UHLBehaviorTree.BTD_Base")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_InAngle",NewName="/Script/UHLBehaviorTree.BTD_InAngle")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_InRange",NewName="/Script/UHLBehaviorTree.BTD_InRange")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_RandomChance",NewName="/Script/UHLBehaviorTree.BTD_RandomChance")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_LoopRandomCount",NewName="/Script/UHLBehaviorTree.BTD_LoopRandomCount")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_TimeLimitRandom",NewName="/Script/UHLBehaviorTree.BTD_TimeLimitRandom")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_GameplayEffectCooldown",NewName="/Script/UHLBehaviorTree.BTD_GameplayEffectCooldown")
+ClassRedirects=(OldName="/Script/UHLAI.BTD_CheckGASGameplayTagsOnActor",NewName="/Script/UHLBehaviorTree.BTD_CheckGASGameplayTagsOnActor")

; BT Composites
+ClassRedirects=(OldName="/Script/UHLAI.BTC_RandomSelector",NewName="/Script/UHLBehaviorTree.BTC_RandomSelector")

; Structs
+StructRedirects=(OldName="/Script/UHLAI.UHLValueOrBBKey_GameplayTag",NewName="/Script/UHLBehaviorTree.UHLValueOrBBKey_GameplayTag")
+StructRedirects=(OldName="/Script/UHLAI.OperationOnBBValue",NewName="/Script/UHLBehaviorTree.UHLBTOperationOnBBValue")
+StructRedirects=(OldName="/Script/UHLAI.AngleRange",NewName="/Script/UHLBehaviorTree.AngleRange")

; Enums
+EnumRedirects=(OldName="/Script/UHLAI.EUHL_MathOperations",NewName="/Script/UHLBehaviorTree.EUHL_MathOperations")
+EnumRedirects=(OldName="/Script/UHLAI.EBlackboardValueType",NewName="/Script/UHLBehaviorTree.EBlackboardValueType")
+EnumRedirects=(OldName="/Script/UHLAI.ETaskNodeEndPolicy",NewName="/Script/UHLBehaviorTree.ETaskNodeEndPolicy")
+EnumRedirects=(OldName="/Script/UHLAI.EScalableChanceType",NewName="/Script/UHLBehaviorTree.EScalableChanceType")


; Redirect classes moved from UHLAI -> UHLBehaviorTree
; BT Tasks
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_TurnTo",NewName="/Script/UHLBehaviorTree.BTT_TurnTo")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_FireGameplayEvent",NewName="/Script/UHLBehaviorTree.BTT_FireGameplayEvent")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_SetBBValue",NewName="/Script/UHLBehaviorTree.BTT_SetBBValue")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_InvokeGameplayAbility",NewName="/Script/UHLBehaviorTree.BTT_InvokeGameplayAbility")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_PlayAnimMontage",NewName="/Script/UHLBehaviorTree.BTT_PlayAnimMontage")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_DebugPrintBBValue",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintBBValue")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_ClearFocus",NewName="/Script/UHLBehaviorTree.BTT_ClearFocus")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTT_DebugPrintString",NewName="/Script/UHLBehaviorTree.BTT_DebugPrintString")

; BT Services
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTS_GameplayFocus",NewName="/Script/UHLBehaviorTree.BTS_GameplayFocus")

; BT Decorators
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_Base",NewName="/Script/UHLBehaviorTree.BTD_Base")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_InAngle",NewName="/Script/UHLBehaviorTree.BTD_InAngle")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_InRange",NewName="/Script/UHLBehaviorTree.BTD_InRange")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_RandomChance",NewName="/Script/UHLBehaviorTree.BTD_RandomChance")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_LoopRandomCount",NewName="/Script/UHLBehaviorTree.BTD_LoopRandomCount")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_TimeLimitRandom",NewName="/Script/UHLBehaviorTree.BTD_TimeLimitRandom")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_GameplayEffectCooldown",NewName="/Script/UHLBehaviorTree.BTD_GameplayEffectCooldown")
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTD_CheckGASGameplayTagsOnActor",NewName="/Script/UHLBehaviorTree.BTD_CheckGASGameplayTagsOnActor")

; BT Composites
+ClassRedirects=(OldName="/Script/UnrealHelperLibrary.BTC_RandomSelector",NewName="/Script/UHLBehaviorTree.BTC_RandomSelector")

; Structs
+StructRedirects=(OldName="/Script/UnrealHelperLibrary.UHLValueOrBBKey_GameplayTag",NewName="/Script/UHLBehaviorTree.UHLValueOrBBKey_GameplayTag")
+StructRedirects=(OldName="/Script/UnrealHelperLibrary.OperationOnBBValue",NewName="/Script/UHLBehaviorTree.UHLBTOperationOnBBValue")
+StructRedirects=(OldName="/Script/UnrealHelperLibrary.AngleRange",NewName="/Script/UHLBehaviorTree.AngleRange")

; Enums
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.EUHL_MathOperations",NewName="/Script/UHLBehaviorTree.EUHL_MathOperations")
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.EBlackboardValueType",NewName="/Script/UHLBehaviorTree.EBlackboardValueType")
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.ETaskNodeEndPolicy",NewName="/Script/UHLBehaviorTree.ETaskNodeEndPolicy")
+EnumRedirects=(OldName="/Script/UnrealHelperLibrary.EScalableChanceType",NewName="/Script/UHLBehaviorTree.EScalableChanceType")
